#!/usr/bin/env bash

## backup main .zshrc ( if exixt )
mv ~/.zshrc .zshrc.bkupp 2> /dev/null

## create dir
mkdir -p ~/.config/zshhh
cp -r . ~/.config/zshhh/

echo "export ZDOTDIR=\"$HOME/.config/zsh\"" >> ~/.zshenv2
exec zsh
echo "$ZDOTDIR"
